### ISSUE TITLE
Storage choices... 

### ISSUE THREAD

**Issue by JadedChara** [CharaHarimata/Terminus-game-dev#2]
@Minion3665 Should I just default the initPlayer() function to reference repl.it's DB, or allow for any to be used? The main reason I'm wondering is because I want to be able to store playerdata for easy saving, but I don't want the function's inputs to be too lengthy. Yes, there's a fair bit of customization involved in the layout for this project, but I want it to also be easy to use and memorize.

**Comment by JadedChara** [comment]
Might switch to a datastore function so as to allow users to choose how they initialize players. Not sure yet...

**Comment by Minion3665** [comment]
I'd say a lengthy list of optional parameters is probably better than having nonstandardized functions

I believe you're using javascript, it may be worth using named optional parameters [as suggested in this medium article](https://medium.com/dailyjs/named-and-optional-arguments-in-javascript-using-es6-destructuring-292a683d5b4e), as that would mean people only have to remember and input the arguments they need.

Hopefully that mostly answers your question, if it doesn't, feel free to ping me again with what I failed to answer and I'll do my best to help you

**Comment by JadedChara** [comment]
It's definitely a lot easier to manage regular functions within functions, than it is for event handlers.
```node
function myfunc(){
  function help(){
    console.log("help message")
  }
  function subfunc(variable){
    console.log(variable)
  }
}

var myfunc = myfunc();
myfunc.subfunc(variable);

```

I'm pretty sure this is how it would be formatted if I wanted to make niche functions?

**Comment by Minion3665** [comment]
*Note: github seems to not show the whole of this reply if you're using the mobile app. If you can't see up to `[End of reply]` then I'd suggest using the web version*

> It's definitely a lot easier to manage regular functions within functions, than it is for event handlers.
> 
> ```node
> 
> function myfunc(){
> 
>   function help(){
> 
>     console.log("help message")
> 
>   }
> 
>   function subfunc(variable){
> 
>     console.log(variable)
> 
>   }
> 
> }
> 
> 
> 
> var myfunc = myfunc();
> 
> myfunc.subfunc(variable);
> 
> 
> 
> ```
> 
> 
> 
> I'm pretty sure this is how it would be formatted if I wanted to make niche functions?

Are you sure? I'd expect the return value of `myfunc()` to be undefined, and therefore for you to be trying to call the property `.subfunc` of undefined and it to fail

It seems to me like you'd have to use classes
```node
class MyClass{
  help(){
    console.log("help message")
  }
  subfunc(variable){
    console.log(variable)
  }
}

var myclass = new MyClass();
myclass.subfunc(variable);
```
or `this`
```node
function myfunc(){
  function help(){
    console.log("help message")
  }
  function subfunc(variable){
    console.log(variable)
  }
  this.subfunc = subfunc;
  this.help = help;
  return this;
}

var myfunc = myfunc();
myfunc.subfunc(variable);
```
to get the desired result.

You could also just return the functions, or set the property subfunc of myfunc outside of myfunc's body, but neither of them do quite what you asked for.

[End of reply]

**Comment by JadedChara** [comment]
I completely forgot about `this.< >`! Thanks for pointing that out! When declaring handlers within functions, are they active the moment the function is run, or can they only be utilized while the function's active?

Something like this is what I'd like to achieve, but I don't know if anything needs to be done prior to utilizing it. I'm in the process of setting up the html, so there's nothing to actually reference for Socket.
```node
function myfunc(){
  socket.on('connection', function(){
    //Some random code snippet
  })
}
myfunc();

//~~~~~
//front-end
//I already know socket.emit() works when nested in a function, but does it communicate of the socket.on() is as well?
socket.emit('<Some Specific Case>')

```

**Comment by JadedChara** [comment]
Oh, wait. Nevermind on the last bit. I found a way it might work. I'll try it out.

**Comment by JadedChara** [comment]
IT WORKS! I tried it out in my old framework, and it still functions! I was not even expecting it to work.

**Comment by JadedChara** [comment]
Okay, so rather than trying to serve a bunch of different htmls, I'm gonna' just use a grid and hide/show elements accordingly. Honestly, that's probably the most I'm willing to do for the demo, because most of my work is going into the scripting.
