### ISSUE TITLE
Major Issue: Cause unknown, but client no longer communicates with server...

### ISSUE THREAD

**Issue by JadedChara** [CharaHarimata/Terminus-game-dev#6]
The current iteration of the code no longer facilitates a connection. After throwing in an error check, I still can't determine the root cause. Help is SEVERELY needed for fixing this. For clarification, I'm using Repl.it. Currently, my suspicion is that it could be the school network causing an issue, but I'm thinking I messed something up somewhere. I just. can't find it.

**Comment by JadedChara** [comment]
Additionally, ```var express = require('express')``` does not recognize 'express' as a valid module.

**Comment by JadedChara** [comment]
@Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol

**Comment by Minion3665** [comment]
> @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol

I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?

Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file

**Comment by JadedChara** [comment]
> > @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol
> 
> I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?
> 
> Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file

I've tried both suggested methods. The server starts and the html is served, but since express seems to be having some issues, the actual /static/script.js file is not connected. The static folder is recognized by the html directly, but it might be a file system issue or something?

**Comment by JadedChara** [comment]
> > > @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol
> > 
> > 
> > I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?
> > Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file
> 
> I've tried both suggested methods. The server starts and the html is served, but since express seems to be having some issues, the actual /static/script.js file is not connected. The static folder is recognized by the html directly, but it might be a file system issue or something?

I've also tried both `app.listen` and `server.listen` so it's not really an issue in that regard. As far as I know, `var server = http.Server(app)` should work for both.

**Comment by Minion3665** [comment]
> > > > @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol
> > > 
> > > 
> > > I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?
> > > Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file
> > 
> > 
> > I've tried both suggested methods. The server starts and the html is served, but since express seems to be having some issues, the actual /static/script.js file is not connected. The static folder is recognized by the html directly, but it might be a file system issue or something?
> 
> I've also tried both `app.listen` and `server.listen` so it's not really an issue in that regard. As far as I know, `var server = http.Server(app)` should work for both.

CNR: I've run a local copy and am not facing this issue; express is not reporting any issues & /static/script.js works fine. /script.js seemed to have a couple of missing brackets but adding them back in fixed everything & I never got all the errors you've seen.

Socket connection seems to be working too evidenced by joining 2 players and seeing them both in the list

**Comment by Minion3665** [comment]
> > > > > @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol
> > > > 
> > > > 
> > > > I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?
> > > > Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file
> > > 
> > > 
> > > I've tried both suggested methods. The server starts and the html is served, but since express seems to be having some issues, the actual /static/script.js file is not connected. The static folder is recognized by the html directly, but it might be a file system issue or something?
> > 
> > 
> > I've also tried both `app.listen` and `server.listen` so it's not really an issue in that regard. As far as I know, `var server = http.Server(app)` should work for both.
> 
> CNR: I've run a local copy and am not facing this issue; express is not reporting any issues & /static/script.js works fine. /script.js seemed to have a couple of missing brackets but adding them back in fixed everything & I never got all the errors you've seen.
> 
> Socket connection seems to be working too evidenced by joining 2 players and seeing them both in the list

See https://github.com/Minion3665/Terminus-game-dev/commit/f9b8c57cec7f71d3d3ba95ec22e5a743fcbe0651 for the code that works for me; as you can see, not much has changed

**Comment by JadedChara** [comment]
> > > > > > @Minion3665 Any suggestions? It returns a 'Could not find a declaration file' error, even when I explicitly have express.d.ts in the files. What did I break lol
> > > > > 
> > > > > 
> > > > > I'll take a look; in the meantime have you considered using [`@types/express`](https://www.npmjs.com/package/@types/express) instead of writing your own?
> > > > > Many NPM packages have typing info in definitelytyped like this, so it's often worth checking before writing your own type file
> > > > 
> > > > 
> > > > I've tried both suggested methods. The server starts and the html is served, but since express seems to be having some issues, the actual /static/script.js file is not connected. The static folder is recognized by the html directly, but it might be a file system issue or something?
> > > 
> > > 
> > > I've also tried both `app.listen` and `server.listen` so it's not really an issue in that regard. As far as I know, `var server = http.Server(app)` should work for both.
> > 
> > 
> > CNR: I've run a local copy and am not facing this issue; express is not reporting any issues & /static/script.js works fine. /script.js seemed to have a couple of missing brackets but adding them back in fixed everything & I never got all the errors you've seen.
> > Socket connection seems to be working too evidenced by joining 2 players and seeing them both in the list
> 
> See [Minion3665@f9b8c57](https://github.com/Minion3665/Terminus-game-dev/commit/f9b8c57cec7f71d3d3ba95ec22e5a743fcbe0651) for the code that works for me; as you can see, not much has changed

Okay, the bracket change worked! Thank you. I absolutely would have missed that since Replit never marked them as missing on my end. I was beginning to get worried.
